name: 'ecommerce_analytics'
version: '1.0.0'
config-version: 2

profile: 'ecommerce_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  payment_methods: ['credit_card', 'paypal', 'bank_transfer', 'gift_card']
  order_statuses: ['pending', 'processing', 'shipped', 'delivered', 'cancelled', 'returned']

models:
  ecommerce_analytics:
    staging:
      +materialized: view
      +schema: staging
      +tags: ['staging', 'daily']
    intermediate:
      +materialized: table
      +tags: ['intermediate']
    marts:
      core:
        +materialized: table
        +schema: marts
        +tags: ['marts', 'core']
      finance:
        +materialized: table
        +schema: marts_finance
        +tags: ['marts', 'finance']
      marketing:
        +materialized: table
        +schema: marts_marketing
        +tags: ['marts', 'marketing']
